### ISSUE TITLE
mdmp false install

### ISSUE THREAD

**Issue by rivaldealer** [radare/radare2-extras#136]
I got inspired by the radare.today post about analyzing minidumps with r2 and followed along.
I've installed radare from the git master repo and then installed r2pm.
However, every time I try to install mdmp this is the console output:
~~~bash
r2pm -i mdmp
Already up-to-date.
Install Done For mdmp
checking build system type... x86_64-unknown-darwin
checking host system type... x86_64-unknown-darwin
checking target system type... x86_64-unknown-darwin
checking for working directories... current
using prefix '/Users/rivaldealer/.config/radare2/prefix'
checking for c compiler... gcc
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_core... no
This package is required
~~~
Two things to note
1. "Install Done for mdmp"
Not quite a convincing install with the last words of "This package is required." I checked the directory `~/.config/radare2/plugins `and no plugins are in the folder.
2. "using prefix '/Users/rivaldealer/.config/radare2/prefix'
Similar to the above issue, the file `prefix` doesn't exist.

I'm not quite sure what to do. I made sure that my own PKG_CONFIG_PATH is set to `/usr/local/lib/pkgconfig` , but that wasn't the remedy it was looking for I'm afraid.

Thank you to any and all help,
Cheers! 🍺

**Comment by radare** [comment]
Works for me

**Comment by rivaldealer** [comment]
May I ask for your `r2pm -i mdmp` output?

**Comment by radare** [comment]
Do you have pkg-config installed in the system? And r2 from git?

**Comment by XVilka** [comment]
Not applicable anymore, since mdmp is now part of r2 itself.

**Comment by Maijin** [comment]
I have updated the blog post to avoid this, hopefully the radare.today got updated quickly ^^

**Comment by radare** [comment]
We may remoce the r2pm package too if it wasnt done already
