### ISSUE TITLE
Current VERSION from configure.acr is too old

### ISSUE THREAD

**Issue by montekki** [radare/radare2-extras#142]
radare2 core has VERSION == 2.1.0-git, however here we have 2.0.0 so when both r2 and extras are installed from git, r2 cannot find extras, since they are in the wrong DESTDIR

**Comment by radare** [comment]
I only bump extras configure before the release. Is this a real problem? Destdir is specified by the user not the version. And if u care about versioned paths, those usually have a symlink names last/ that should do the job

**Comment by montekki** [comment]
ok
