### ISSUE TITLE
r2angr ImportError

### ISSUE THREAD

**Issue by dack** [radare/radare2-extras#147]
After installing r2angr plugin:

```
$ r2 /bin/ls
Traceback (most recent call last):
  File "/home/ctf/.config/radare2/plugins/r2angr-io.py", line 13, in <module>
    import r2lang
ImportError: No module named r2lang

```

I can't seem to find the "r2lang" python library anywhere. What provides this? Should r2pm have auto installed it as a dependency for r2angr? Or is it an out of date library reference?

**Comment by radare** [comment]
r2pm -i lang-python3 (or 2)

**Comment by dack** [comment]
Ah, that's the one thanks.
