### ISSUE TITLE
r2pm -i evm failed

### ISSUE THREAD

**Issue by n0pn0pn0p** [radare/radare2-extras#185]
i'm trying "r2pm -i evm" on my mac, but i got 
dare2/prefix/lib'
ld: warning: directory not found for option '-L../../util'
ld: warning: directory not found for option '-L../../lib'
Undefined symbols for architecture x86_64:
  "_opcodes", referenced from:
      _evm_oplen in anal_evm.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [anal_evm.dylib] Error 1
make[1]: *** [evm] Error 2
make: *** [evm] Error 2

i don't know how to solve? plz help me,  thx!

**Comment by 0xXA** [comment]
Remove it

**Comment by radare** [comment]
?

**Comment by fgsch** [comment]
Should be addressed by https://github.com/radare/radare2-extras/pull/186.
