### ISSUE TITLE
r2pm install evm filed

### ISSUE THREAD

**Issue by ouerum** [radare/radare2-extras#188]
I use r2pm to install radare2-extras in my macos and ubuntu, but it failed. There is the some message about it:
anal_evm.c:4:10: fatal error: 'jansson.h' file not found
#include <jansson.h>
         ^~~~~~~~~~~
1 error generated.
make[2]: *** [anal_evm.o] Error 1
make[1]: *** [evm] Error 2
make: *** [evm] Error 2

Why 'jansson.h' file not found when I install? please tell me, thanks.

**Comment by radare** [comment]
just install jansson from your distro and i t will compile
