### ISSUE TITLE
RIOSection in libr/debug/p/debug_unicorn.c 

### ISSUE THREAD

**Issue by dissonant-research** [radare/radare2-extras#196]
"r2pm install unicorn" fails with current radare2 (3.5.1)
RIOSection libr type was removed as of 3.3.0
radare2-extras/libr/debug/p/debug_unicorn.c still uses RIOSection

> debug_unicorn.c: In function ‘r_debug_unicorn_init’:
> debug_unicorn.c:513:2: error: unknown type name ‘RIOSection’; did you mean ‘RBinSection’?
>   RIOSection *sect;
>   ^~~~~~~~~~

**Comment by radare** [comment]
Should use RIOMap, and riosection should be gone in 2.x so its not a recent api change at all. Should be easy to fix to use the new apis

Do you want to try?

**Comment by dissonant-research** [comment]
#197 pull request

**Comment by dissonant-research** [comment]
#198 pull request (#197 was broken)

**Comment by radare** [comment]
Thanks!!
