### ISSUE TITLE
Building and using radare2-extras.

### ISSUE THREAD

**Issue by Anon2016** [radare/radare2-extras#26]
Hi,
I want use radare2 for analyze programs  written for processors BlackFin. As I understand, disassembler for BlaskFin contains only in radare2-extras branch. I installed radare2 on Ubuntu as it describe in https://github.com/radare/radare2 . As I understand, now i should build radare2-extras for add BlackFin disassembler in radare2. I used git clone and get file from https://github.com/radare/radare2-extras , this file contains in home folder. After this I try build radare2-extras as it describe in https://github.com/radare/radare2-extras , but I meet the following challenges: 
After 
./configure --prefix=/usr
make baleful
I can't found baleful-install and can't use make for this.
Sorry for stupid question, but what I should to do? Should I download or install another packet? Should I make radare2-extras with file, contains in main branch?

**Comment by radare** [comment]
You can check the r2pm packages to list, build and install them

**Comment by Anon2016** [comment]
Yes, it works! Thanks!
