### ISSUE TITLE
Without debugger handler for Unicorn

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2-extras#27]
Try to install unicorn plugin to radare2 but don't see in list:

```
$ r2 /bin/ls
[0x00404890]> dh unicorn
[0x00404890]>
[0x00404890]> dh?
0  ---  wind     LGPL3
1  ---  rap      LGPL3
2  dbg  native   LGPL3
3  ---  gdb      LGPL3
4  ---  esil     LGPL3
5  ---  bf       LGPL3
```

Unicorn work. For install used readme-file https://github.com/radare/radare2-extras/tree/master/unicorn

P.S. May be add some text for absent debuggers?

**Comment by radare** [comment]
I guess latest unicorn-git is not friendly with the plugin. It should be updated at some point.

U can run r2 with the debug env vars set to see which symbols are missing or the reason why its not loading

You can install unicorn and unicorn-lib with r2pm

**Comment by dukebarman** [comment]
How can I setup debug env for r2?

**Comment by radare** [comment]
Export R_DEBUG=1

**Comment by dukebarman** [comment]
thx,

```
dlerror(/home/usermint/.config/radare2/plugins/debug_unicorn.so): /home/usermint/.config/radare2/plugins/debug_unicorn.so: undefined symbol: uc_hook_add
Cannot open library: '/home/usermint/.config/radare2/plugins/debug_unicorn.so'
```

**Comment by radare** [comment]
cannot reproduce uc_hook_add is already in the latest unicornn lib from git.. did you installed the lib and the plugin with r2pm?

**Comment by dukebarman** [comment]
I installed with r2pm:
```
~/.config/radare2/r2pm/git/unicorn $ nm libunicorn.so | grep uc_hook_add
00000000007a3530 T uc_hook_add
$ nm ../radare2-extras/libr/debug/p/debug_unicorn.so | grep uc_hook_add
                 U uc_hook_add
```

**Comment by radare** [comment]
libunicorn should be in LD_LIBRARY_PATH, what do ldd tells you about debug_unicorn.so?

**Comment by dukebarman** [comment]
```
$ ldd ../radare2-extras/libr/debug/p/debug_unicorn.so
	linux-vdso.so.1 =>  (0x00007fff94fb1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2502dea000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f25033da000)
```

**Comment by radare** [comment]
so its not linking against libunicorn. how did you compiled this? :P

**Comment by dukebarman** [comment]
I wrote above - with r2pm :)
```
$ r2pm -i unicorn-lib
$ r2pm -i unicorn
```

**Comment by crowell** [comment]
crappy workaround 

```bash
gcc -shared -o debug_unicorn.so debug_unicorn.o /usr/lib/libunicorn.a -L/usr/lib -lunicorn -lglib-2.0 -lpthread -lm -I/usr/include/libr -lr_core -lr_config -lr_cons -lr_util -lr_flags -lr_asm -lr_db -lr_debug -lr_hash -lr_bin -lr_lang -lr_io -lr_anal -lr_parse -lr_bp -lr_egg -lr_reg -lr_search -lr_syscall -lr_socket -lr_fs -lr_magic
```

**Comment by radare** [comment]
its building fine here not sure which is your problem

**Comment by radare** [comment]
can you paste the build line that is making libunicorn not linked against libunicorn?

**Comment by dukebarman** [comment]
It's a build log for Linux Mint 17 http://pastebin.com/eCb13S7V

**Comment by radare** [comment]
its linking here:

        -I/usr//include -L/usr//lib -lunicorn \
