### ISSUE TITLE
r2pm -u doesn't work correctly

### ISSUE THREAD

**Issue by dukebarman** [radare/radare2-extras#30]
Option `-u plugin` doesn't delete plugin's files from `~/.confg/radare2/...` so I need delete this folder for normal work.

For example:
- I tried to install a new version of unicorn (with patch) but r2pm installed old version.
- I tried install unicorn plugin on other comp and haven't got libglibc2.0-dev package so process was stopped. And I couldn't restart install because some files from qemu had other permissions (`~/.config/radare2/r2pm/git/unicorn/qemu/config-temp/*`)

**Comment by radare** [comment]
it shoulkd ,which plugin are you talking about?

**Comment by dukebarman** [comment]
unicorn-lib and may be unicorn too

**Comment by Maijin** [comment]
status @dukebarman

**Comment by dukebarman** [comment]
Better. But folder `~/.config/radare2/r2pm/git/unicorn` isn't delete

**Comment by radare** [comment]
this is deleted with r2pm -c

**Comment by Maijin** [comment]
ok closing
