### ISSUE TITLE
keystone build fails because -lc++ flag used

### ISSUE THREAD

**Issue by j123123** [radare/radare2-extras#70]
In this commit https://github.com/radare/radare2-extras/commit/467d4785ce8f341371cffb52b59127a8bbac478f flag ``-lc++`` is added, and compiling fails:
````
$ r2pm -i keystone
r_config_set: variable 'file.id' not found
r_config_set: variable 'file.flag' not found
r_config_set: variable 'file.analyze' not found
Processing keystone ...
Already up-to-date.
Install Done For keystone
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for working directories... current
using prefix '/home/user/.config/radare2/prefix/'
checking for c compiler... gcc
checking for c++ compiler... g++
checking for libkeystone ... yes
Using PKGCONFIG: pkg-config
checking pkg-config flags for r_asm... yes
creating ./config.mk
cleaning temporally files... done
rm -f *.so
make asm_arm_ks.so
make[1]: Entering directory `/home/user/.config/radare2/r2pm/git/radare2-extras/keystone'
gcc -lc++ -fPIC -shared -Wall -I/usr/include/libr -lr_asm -lr_syscall -lr_lang -lr_util -lr_parse -lr_flags -lr_cons -lr_reg -lr_anal -I/usr/local/include   -L/usr/local/lib -lkeystone   -o asm_arm_ks.so asm_arm_ks.c -lkeystone
/usr/bin/ld: cannot find -lc++
collect2: error: ld returned 1 exit status
make[1]: *** [asm_arm_ks.so] Error 1
make[1]: Leaving directory `/home/user/.config/radare2/r2pm/git/radare2-extras/keystone'
make: *** [arm] Error 2
````
I had to edit Makefile and remove this ``-lc++`` flag. Maybe on some OS-es this flag is important
OS: Ubuntu 14.04.5 LTS if this matters

**Comment by radare** [comment]
Did u r2pm update?

> On 22 Oct 2016, at 18:24, szt <notifications@github.com> wrote:
> 
> In this commit 467d478
> 
> $ r2pm -i keystone
> r_config_set: variable 'file.id' not found
> r_config_set: variable 'file.flag' not found
> r_config_set: variable 'file.analyze' not found


Clean your radare2rc

> Processing keystone ...
> Already up-to-date.
> Install Done For keystone
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for working directories... current
> using prefix '/home/user/.config/radare2/prefix/'
> checking for c compiler... gcc
> checking for c++ compiler... g++
> checking for libkeystone ... yes
> Using PKGCONFIG: pkg-config
> checking pkg-config flags for r_asm... yes
> creating ./config.mk
> cleaning temporally files... done
> rm -f *.so
> make asm_arm_ks.so
> make[1]: Entering directory `/home/user/.config/radare2/r2pm/git/radare2-extras/keystone'
> gcc -lc++ -fPIC -shared -Wall -I/usr/include/libr -lr_asm -lr_syscall -lr_lang -lr_util -lr_parse -lr_flags -lr_cons -lr_reg -lr_anal -I/usr/local/include   -L/usr/local/lib -lkeystone   -o asm_arm_ks.so asm_arm_ks.c -lkeystone
> /usr/bin/ld: cannot find -lc++
> collect2: error: ld returned 1 exit status
> make[1]: *** [asm_arm_ks.so] Error 1
> make[1]: Leaving directory `/home/user/.config/radare2/r2pm/git/radare2-extras/keystone'
> make: *** [arm] Error 2
> I had to edit Makefile and remove this -lc++ flag. Maybe on sime OS-es this flag is important
> OS: Ubuntu 14.04.5 LTS if this matter
> 

Can you send a pr?

**Comment by j123123** [comment]
>Did u r2pm update?
...
>Clean your radare2rc

This may not affect this issue. If you try to do compile some c++ code with ``-lc++`` on some linux distro without libcxx, it will fail.
````
$ cat text.c++ 
#include <iostream>
int main(){ std::cout << 1; return 0;}
$ g++ -lc++ text.c++
/usr/bin/ld: cannot find -lc++
collect2: error: ld returned 1 exit status
````

**Comment by radare** [comment]
so what do you propose? tell the user in a human way that their system is fuckedup?

i think debian is the only stupid distro that allows to install g++ without libcxx-dev as a dependency

**Comment by j123123** [comment]
libcxx-dev is LLVM C++ standard library. g++ use libstdc++ (GNU Standard C++ Library), with flag ``-lstdc++`` (this flag is enabled by default). keystone can be compiled with it and works without any visible problem.

**Comment by radare** [comment]
so?

**Comment by j123123** [comment]
so why you need libcxx dependency if it works with libstdc++ ?

**Comment by radare** [comment]
i dont need it, im asking you about what’s the best solution you think we should use, because the pkg is already using -lc++ and not -lcxx. and the way it is right now works in all my machines, so which solution do you suggest?

**Comment by j123123** [comment]
I suggest to remove ``-lc++`` flag.

Or make some configure script which check if libcxx or libstdc++ availabe and generate Makefile with ``-lc++`` or ``-lstdc++``

**Comment by Maijin** [comment]
@j123123 Pull request please

**Comment by j123123** [comment]
``undefined symbol: __cxa_pure_virtual`` happens if keystone compiled wit this ``-lstdc++``

````
$ export R_DEBUG=1
$ rasm2 -L
dlerror(/home/user/.config/radare2/plugins/asm_sparc_ks.so): /home/user/.config/radare2/plugins/asm_sparc_ks.so: undefined symbol: __cxa_pure_virtual
Cannot open library: '/home/user/.config/radare2/plugins/asm_sparc_ks.so'
dlerror(/home/user/.config/radare2/plugins/asm_arm_ks.so): /home/user/.config/radare2/plugins/asm_arm_ks.so: undefined symbol: __cxa_pure_virtual
Cannot open library: '/home/user/.config/radare2/plugins/asm_arm_ks.so'
dlerror(/home/user/.config/radare2/plugins/asm_hexagon_ks.so): /home/user/.config/radare2/plugins/asm_hexagon_ks.so: undefined symbol: __cxa_pure_virtual
Cannot open library: '/home/user/.config/radare2/plugins/asm_hexagon_ks.so'
dlerror(/home/user/.config/radare2/plugins/asm_x86_ks.so): /home/user/.config/radare2/plugins/asm_x86_ks.so: undefined symbol: __cxa_pure_virtual
Cannot open library: '/home/user/.config/radare2/plugins/asm_x86_ks.so'
dlerror(/home/user/.config/radare2/plugins/asm_ppc_ks.so): /home/user/.config/radare2/plugins/asm_ppc_ks.so: undefined symbol: __cxa_pure_virtual
....
````
https://stackoverflow.com/questions/7397302/why-cant-i-link-a-mixed-c-c-static-library-that-has-a-c-interface-using-gcc

**Comment by radare** [comment]
<3 c++

**Comment by j123123** [comment]
OK, looks like I fixed it. Wait for PR
